### ISSUE TITLE
a slightly modified approach

### ISSUE THREAD

**Issue by mpadge** [deanmarchiori/culburra#1]
Hey @deanmarchiori, great map, great code, and I'm chuffed that you're using my packages to create such beautiful results! If i may, the following `reprex` shows a few slightly more efficient ways to get your end result, particularly by removing all of the `sf` manipulations and the hand-selection of `osm_id` values. These can simply be replaced by the dodgr ability to select the largest connected component, which is what you want here. The only actual coordinate manipulation then necessary is to trim the data from the far east, so the single coordinate enters in the form of `xmin`. (Note that you might be latest dev versions of both `osmdata` and `dodgr` for this to work flawlessly.)

``` r
library (dplyr)
library (forcats)
library (ggplot2)
library (osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
library (dodgr)

streets_raw <- opq ("culburra beach, NSW, Australia") %>%
    add_osm_feature (key = "highway") %>%
    osmdata_sf () %>%
    osm_poly2line ()

xmin <- 150.74

streets_raw <- weight_streetnet (streets_raw$osm_lines) %>%
    filter (component == 1) %>%
    filter (from_lon > xmin & to_lon > xmin) %>%
    dodgr_to_sf ()
#> Loading required namespace: sf

streets <- streets_raw %>% 
  select(edge_id, highway) %>% 
  mutate(highway = fct_recode(highway, 
                              residential = "service",
                              residential = "unclassified",
                              path = "track",
                              path = "cycleway"
                              )) 

ggplot(streets, aes(col = highway)) +
  geom_sf(data = filter(streets, highway == 'path'), alpha = 0.4, show.legend = F) +
  geom_sf(data = filter(streets, highway == 'residential'), alpha = 0.5, show.legend = F) +
  geom_sf(data = filter(streets, highway == 'secondary'), alpha = 0.9, show.legend = F) +
  scale_colour_manual(values =  c("path" = "#70838B", 
                                  "residential" = "#0A5D81", 
                                  "secondary" = "#0A5D81")) +
  labs(caption = "Culburra Beach",
       y = "") +
  #expand_limits(y = c(-34.8980, -34.9482)) + 
  theme_minimal() +
  theme(
    plot.background = element_rect(fill = "#E4D9C6", color = NA),
    panel.background = element_rect(fill = "#E4D9C6",  color = NA),
    panel.grid = element_blank(), 
    axis.text = element_text(colour = "#C7B18A", family = "Ubuntu Mono"),
    axis.ticks = element_blank(), 
    panel.border = element_blank(), 
    plot.caption = element_text(family = "Ubuntu Mono", size = 85, vjust = -0.2, color = '#C7B18A'), 
    plot.margin = margin(22,10,22,10, "mm"))
```

![](https://i.imgur.com/r03YPww.png)

<sup>Created on 2020-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Great work! And feel free to close this immediately and ignore it, as your map has obviously already been generated ...

**Comment by deanmarchiori** [comment]
G'day @mpadge,

Firstly, thanks for your work in developing these packages. I was really excited to use them, so excited in fact I perhaps did things a little clumsily. I have a few more maps I'd like to make and will try out your suggestions for sure. 

Thanks again for you feedback and taking the time to help out.

**Comment by mpadge** [comment]
On another note: If you like, you could share this repo with the broader rOpenSci community by adding it as a [Use Case](https://discuss.ropensci.org/c/usecases/10) - obvious self-interest at work there on my part :smirk: coz you'd be publicising my package, but hey, that's how it works these days. Otherwise i could do it with your permission to share your image.

**Comment by deanmarchiori** [comment]
Sounds like a good idea. I'm not sure how to do it, but if you would like to submit it, I am happy for you to share the image and code etc.

**Comment by mpadge** [comment]
Thanks - new entry is [here](https://discuss.ropensci.org/t/osmdata-use-case-wall-art/1944). You can use github to SSO-log on and comment if you like - hopefully somebody might even comment on your great image!
